server:
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 90s
  max_idle_conns: 100
  max_idle_conns_host: 10
  handshake_timeout: 10s
  response_timeout: 30s

logging:
  level: info
  format: json
  output: stdout

upstreams:
  - url: "http://localhost:8010/v1/graphql"
    capabilities:
      - mutation
    operation_names:
      - getUserProfile
      - updateUserProfile
      - test
    weight: 2
  - url: "http://localhost:8011/v1/graphql"
    capabilities:
      - query
      - mutation
    operation_names:
      - test
    weight: 1
  - url: "http://localhost:8012/v1/graphql"
    capabilities:
      - query
      - subscription
      - mutation
    operation_names:
      - getMetrics
      - subscribeToMetrics
    weight: 1 